### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by bluizh** [udacity/SFND_3D_Object_Tracking#3]
I compiled successfully,but an error occurred when I ran.
```
./3D_object_tracking 
```
#1 : LOAD IMAGE INTO BUFFER done
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.0) /home/kieranych/SFND/opencv/opencv-4.1.0/modules/dnn/src/darknet/darknet_io.cpp:694: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'

Aborted (core dumped)

**Comment by sparshgarg23** [comment]
I am also having the same issues.I saw this link(https://stackoverflow.com/questions/54785928/opencv-implementation-of-yolo-v3-reproduces-exception-on-a-gcp-instance).
Please let me know if redownloading the weights will help in solving this issue.

**Comment by mshong0320** [comment]
same issue here..

**Comment by sparshgarg23** [comment]
redownloading the weights works.
use the following link
wget https://pjreddie.com/media/files/yolov3.weights

wget https://pjreddie.com/media/files/yolov3-tiny.weights

**Comment by heikoschmidt1187** [comment]
Same issue here, even if fetching with git-lfs directly. 
Re-downloading works - thank you for the hint @sparshgarg23

**Comment by ZmeiGorynych** [comment]
I found that if I install git-lfs and run `git lfs install` _before_ cloning the repo, it downloads the weights as part of the cloning and the above exception doesn't occur.

Initially I had cloned before installing git-lfs and then got this exception.

**Comment by wAuner** [comment]
It's unbelievable that they still haven't addressed this issue. It also messes up all my following commits when I replace the file.

**Comment by ZmeiGorynych** [comment]
What is there to fix? You just need to use the repo as intended, ie install git lfs before cloning, and then it all works - am I missing something?

**Comment by wAuner** [comment]
at the very least a hint in the readme....

**Comment by LabRat-Number0** [comment]
June 12. They still have not fixed this or put something meaningful in the readme.

**Comment by LabRat-Number0** [comment]
The easiest way is to have a symbolic link to the dat folder of one of the tutorials (named detect_object).

**Comment by Hagar-Usama** [comment]
> I am also having the same issues.I saw this link(https://stackoverflow.com/questions/54785928/opencv-implementation-of-yolo-v3-reproduces-exception-on-a-gcp-instance).
> Please let me know if redownloading the weights will help in solving this issue.

@sparshgarg23
 where shall I download the weights?

Thanks!

**Comment by Deephome** [comment]
@Hagar-Usama this dir: /dat/yolo

**Comment by Hagar-Usama** [comment]
> @Hagar-Usama this dir: /dat/yolo

Thanks so much :pray:

**Comment by HandMi** [comment]
> at the very least a hint in the readme....

It actually mentions in the readme that LFS is required (https://git-lfs.github.com/). After installiung LFS just remove the weights and do git checkout .

**Comment by abhiojha8** [comment]
Updated the README.
