### ISSUE TITLE
visualization error

### ISSUE THREAD

**Issue by Deephome** [udacity/SFND_3D_Object_Tracking#7]
when I run ./3D_object_tracking , the visualization window is empty, while images are expected to be shown: 
![Screenshot from 2021-03-24 10-32-35](https://user-images.githubusercontent.com/28822327/112245898-c39ba680-8c8c-11eb-9fa3-c1f33d9917de.png)

Anyone can give me some advice?

**Comment by SudKul** [comment]
Hi @Deephome 
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you

**Comment by jiangchaokang** [comment]
I also encountered the same problem, how did you solve it?
